### ISSUE TITLE
Input for the unsupervised branch

### ISSUE THREAD

**Issue by saramsv** [yassouali/CCT#11]
Hi, Thank you so muchfor the great work. 
I am trying to use your implementation for another application. I was wondering if you could give me some info about the file format for the unsupervised branch. 
When I run the code for example I get ['/JPEGImages/2011_003274.jpg', '/SegmentationClassAug/2011_003274.png'] as one example of the 'file_list' generate by 'dataloaders/voc.py' when the 'self.split' is set as 'train_unsupervised'. 
Now my question is, should I expect /SegmentationClassAug/2011_003274.png to have no label or annotation because it is unsupervised? If so, that is not the case, because although /SegmentationClassAug/2011_003274.png seems all black at the first look, the pixels depicting the object in it however, are colored with the value of the their class.

I appreciate your clarification.

**Comment by yassouali** [comment]
Hi @saramsv 
Thank you for your interest.

In a practical case, yes you are right, the unsupervised branch only takes the images without any labels. In our case, given that we only simulate the semi-supervised case by ignoring the labels of already labeled images, we do however load the labels, but they are only used to compute the acc and miou during for printing reasons only, they are not used in training.

In your case, you can create two datasets, one with labels for the supervised branch and any without any for the unsupervised branch. You'll also need to comment out the parts in `trainer.py` that use the labels of the unsupervised dataset (called `target_ul`) to compute the mIoU.

Hope I answered your question.

**Comment by saramsv** [comment]
Thank you so much for your prompt reply. Yes, that makes a lot of sense.
