### ISSUE TITLE
hyperparameter tuning

### ISSUE THREAD

**Issue by lqycrystal** [yassouali/CCT#12]
Hi! Thanks for your great work.
I am also trying to use my own dataset to carry out the experiment, but I find that semi-supervised has only improved 0.5% IoU than full-supervised for my dataset, could you give me some suggestions for hyperparameter tuning in order to improve the result of semi-supervised? 
Thanks.

**Comment by yassouali** [comment]
Hi @lqycrystal 
Thank you for your interest.

I would suggest starting with a simple case, using only a single perturbation / aux. decoder with say only K=2, this will reduce the training time and gives you the ability to find the best hyperparameters (LR, loss weightings and ramp-up period, etc...), then add additional aux. decoders. You can also try using annealed CE that helps with small labeled sets.

I'd also like to note that the performance gain depends on the amount of labeled / unlabeled data, if the difference if big, then SSL helps. But the biggest the labeled set, the smaller the gains are.

**Comment by lqycrystal** [comment]
> Hi @lqycrystal
> Thank you for your interest.
> 
> I would suggest starting with a simple case, using only a single perturbation / aux. decoder with say only K=2, this will reduce the training time and gives you the ability to find the best hyperparameters (LR, loss weightings and ramp-up period, etc...), then add additional aux. decoders. You can also try using annealed CE that helps with small labeled sets.
> 
> I'd also like to note that the performance gain depends on the amount of labeled / unlabeled data, if the difference if big, then SSL helps. But the biggest the labeled set, the smaller the gains are.

Thanks for your reply!
