### ISSUE TITLE
mIoU of unlabeled dataset

### ISSUE THREAD

**Issue by SuzannaLin** [yassouali/CCT#14]
Hello! Thanks for sharing this work. The paper is also very well written!

I want to try this framework on my own dataset. So far, I have run the script using VOC2012, and I notice that during training, the mean IoU is also calculated for the unlabeled dataset.
Do I need to have the segmentation labels of the "unsupervised" images as well? Is there an easy way to go around this?

Thanks :)

**Comment by yassouali** [comment]
Hi @SuzannaLin 
Thank you for your interest.

In our case, given that we only simulate the semi-supervised case by ignoring the labels of already labeled images, we do however load the labels, but they are only used to compute the acc and miou during for printing reasons only, they are not used in training.

In your case, you can create two datasets, one with labels for the supervised branch and any without any for the unsupervised branch. You'll also need to comment out the parts in trainer.py that use the labels of the unsupervised dataset (called target_ul) to compute the mIoU.
