### ISSUE TITLE
using weakly supervised dataset

### ISSUE THREAD

**Issue by SuzannaLin** [yassouali/CCT#15]
Hello Yassine,

I have some questions about adding weakly labeled images.
First, I generated pseudo labels using irn, and the 10.582 .png files were saved correctly. Then, I set use_weak_labels: true in the configs file. However, when I run the main train.py script, it gives me the following error: (see image as well)

TypeError: forward() missing 2 required positional arguments: 'curr_iter' and 'epoch'
(with use_weak_labels: false I do not have this issue)
![image](https://user-images.githubusercontent.com/69157347/94827335-9b7f6900-0408-11eb-8a1d-af9367790e49.png)

Second, how exactly are the pseudo labeled images utilized? When using the weakly labeled method, the model still trains on the labeled and unlabeled datasets as well? With each iteration the same amount of labeled, unlabeled, and pseudo labeled images? Some images will be in the labeled and the pseudo labeled data set, or some in both the unlabeled and pseudo labeled data sets?

I hope my questions are clear. I would appreciate your help.

ps: how many epochs did the model require to achieve the results published in the paper?

**Comment by yassouali** [comment]
Hi @SuzannaLin, thank you for your interest,

I guess you are using `abCE loss`, and in this case, we must also pass `curr_iter` and `epoch` to compute the weighting. I just pushed a correction, you'll simply need to use the `CE` loss.

The correction is simply:

```
loss_weakly = sum([self.sup_loss(outp, target_ul, ignore_index=self.ignore_index) for outp in outputs_ul]) / len(outputs_ul)
```

to

```
 from utils.losses import CE_loss
........
loss_weakly = sum([CE_loss(outp, target_ul, ignore_index=self.ignore_index) for outp in outputs_ul]) / len(outputs_ul)
```


In terms of the usage of weak labels, after generating the pseudo-pixel-level labels, the aux. decoders & encoder are trained with a loss `MSE(aux. pred, main pred) + CE(pseudo labels, aux.pred)`. So we simply use the generated labels to train the aux. decoder using the standard CE.

I hope I answered your question.

**Comment by SuzannaLin** [comment]
Yes! It's working :)
thank you!

**Comment by SuzannaLin** [comment]
Some more questions:
When using the weakly labeled setting, the weakly labeled images are the same as the unlabeled dataset?

Using my own images, I thought about creating 3 different datasets: fully labeled, weakly labeled, and unlabeled dataset. But in the train.py script, there is only the unlabeled dataset (which includes the weakly-labeled images).

Do I need to generate weak labels for all the unlabeled images if I use this setting?

**Comment by yassouali** [comment]
Hi,

As you mentioned, the weakly labeled examples are also considered unlabeled, so they are used for both weakly loss and unsupervised loss.

If you want to use three distinct datasets, labeled, unlabeled, and weak, you'll need to modify the code a little bit where the unlabed and weakly labeled are seperate, but it won't take that much time I think.
