### ISSUE TITLE
inference

### ISSUE THREAD

**Issue by SuzannaLin** [yassouali/CCT#16]
Thank you so far for all the help!

I am now trying to run inference.py on VOC12 images with a semi-supervised trained model.
I filled in the arguments in the script:
![image](https://user-images.githubusercontent.com/69157347/94920692-1010e100-04b7-11eb-998d-983d8d334316.png)

I have two errors:
![image](https://user-images.githubusercontent.com/69157347/94920760-2fa80980-04b7-11eb-8b6c-80552785e8a2.png)
It includes all the aux. decoders (weight and bias).
and:
![image](https://user-images.githubusercontent.com/69157347/94920827-56fed680-04b7-11eb-8955-eb44bf1a3903.png)

Is the first exception an issue for the code?
How do I go about the second error?

**Comment by SuzannaLin** [comment]
I figured out that for inference, I don't actually need all the aux.decoders, so I just removed them from the dictionary. However, the args.save still gives me issues:

AttributeError: 'Namespace' object has no attribute 'save'

**Comment by SuzannaLin** [comment]
I just added 
![image](https://user-images.githubusercontent.com/69157347/94939350-4dcf3300-04d2-11eb-8f88-414304f22cd4.png)

The script runs now without errors, but also without results. The "outputs" dir is created, but empty.

![image](https://user-images.githubusercontent.com/69157347/94939427-6e978880-04d2-11eb-9536-ea042de00070.png)

**Comment by SuzannaLin** [comment]
Never mind, what a mistake I made!
I spelled the images folder wrong! >.<

I have outputs now!

**Comment by yassouali** [comment]
Hi @SuzannaLin 

Sorry for the delay.

Thank you for pointing out the errors, I just pushed the corrections.
