### ISSUE TITLE
saving best model

### ISSUE THREAD

**Issue by SuzannaLin** [yassouali/CCT#23]
Hi Yassine,
During training, is always the latest model saved or only the best?
If the best model is saved, on which metric is that decision based?
For example: This is what I got after 76 epochs
![image](https://user-images.githubusercontent.com/69157347/97078723-4fca7480-15ee-11eb-9b91-ab502cd634c8.png)

but at 78 the model stopped and its mIoU for the EVAL set is lower:
![image](https://user-images.githubusercontent.com/69157347/97078726-5a850980-15ee-11eb-9d17-b2cafa663963.png)

**Comment by yassouali** [comment]
Hi @SuzannaLin the best model is saved based on mIoU, this is specified in the config file `"monitor": "max Mean_IoU"`

**Comment by SuzannaLin** [comment]
Thanks for your answer!
