### ISSUE TITLE
Strange errors when training with 2x GPUs

### ISSUE THREAD

**Issue by PkuRainBow** [yassouali/CCT#24]
Really impressive work and excellent results!

Here we have tried to reproduce your results with 2x 16G V100 GPUs as we have no access to 32G V100 GPUs (your experiment requires 32G V100, right?) 
During the training stage, we also meet the errors as follows:

![image](https://user-images.githubusercontent.com/4639578/97804280-c0762e80-1c89-11eb-947e-3782c5dbc3a9.png)

It would be great if you could give me some advice on possible reasons. My guess is that the PSPNet has a very special global pooling and the BN statics over the global pooled features might cause some errors.

**Comment by yassouali** [comment]
Hi @PkuRainBow, thank you for your interest in our work.

This error is at the end of the first epoch, where in the last batch, you have only one image and BN gives an error, to solve this, please simply set `drop_last = True` in the dataloaders (or change the batch size / do an if statement to skip the last step if BZ = 1).

**Comment by PkuRainBow** [comment]
@yassouali Thanks for your quick reply. I am wondering whether you have compared the final performance of the method trained with 1x 32G V10 GPU and the method trained with 2x 16G V100 GPUs as we want to accelerate the training time.
Especially, we are not sure whether SyncBN is necessary when using 2x GPUs.

**Comment by yassouali** [comment]
@PkuRainBow If I remember correctly; the results are quite similar without the need for sync bn.
