### ISSUE TITLE
Error with Inference

### ISSUE THREAD

**Issue by akmaralAW** [yassouali/CCT#26]
Hello !

I am getting RuntimeError: Error(s) in loading state_dict for DataParallel: size mismatch for module.main_decoder.upsample error. What may cause this error ? I am using images of the same size as for training dataset images. 

Akmaral

**Comment by yassouali** [comment]
Hi @akmaralAW 

Maybe try commenting line 85 (not adding data-parallel)

**Comment by akmaralAW** [comment]
Great ! Works ! Thanks !
