### ISSUE TITLE
SegmentationClassAug for training

### ISSUE THREAD

**Issue by akmaralAW** [yassouali/CCT#27]
Hello !

What is the reason to use SegmentationClassAug instead of SegmentationClass ? 

I've just finished to train the model with common pixel-wise annotated images. And the result is not good. I was wondering maybe it is related to my labels. 

Thanks )

**Comment by yassouali** [comment]
SegmentationClassAug is just a version of pascal voc with more labels, nothing particular.
Maybe different hyperparameters (less aux. decoders, changing the lr) ...

**Comment by akmaralAW** [comment]
OK!
Thank you !
