### ISSUE TITLE
low performance for semi segmentation

### ISSUE THREAD

**Issue by chuxiang93** [yassouali/CCT#3]
I used the same fault config, and tested for 80 epochs. The best mean_iou is 0.718. Is this result within the margin of error？
![image](https://user-images.githubusercontent.com/11666931/87740114-fba43d00-c813-11ea-8467-223d254001a1.png)

**Comment by yassouali** [comment]
hI @mjq93, thank you for your interest in our work;

If you used the exact config, that is 1.5K labels - semi-supervised, the results are correct, in the paper we reported 69.4 after training for 50 epochs, so if you train for 80 epochs, the results seem to be right, about 70-71.

I guess you are referring to 73 mIoU, this is the case where pseudo labels were also used (see paper for more details), to get this performance, you first need to generate the pseudo labels, then run the training with `use_weak_laebls = True`. See readme for more details.

Hope I answered your question.
