### ISSUE TITLE
Evaluation bugs caused performance turn down

### ISSUE THREAD

**Issue by ghost** [yassouali/CCT#42]
Sorry for the wrong post, I just checked that the base size isnot be set in evaluation. However, when I modified the evaluation function to be:
``` python
output = torch.nn.functional.interpolate(output,
                                                              size=(H, W),
                                                              mode='bilinear',
                                                              align_corners=True)
```
instead of 
``` python
output = output[:, :, :H, :W]
```
in [here,](https://github.com/yassouali/CCT/blob/cf98ea7e6aefa7091e6c375a9025ba1e0f6e53ca/trainer.py#L125) the result in my case (which is a custom data-set) increase about 1.5%.

**Comment by Sun-Rider** [comment]
Sorry, I just notice that your base size in evaluation is none.

**Comment by yassouali** [comment]
Hi @Sun-Rider 

Thank you for the remark, maybe others will also find this helpful
