### ISSUE TITLE
How do you get the image?

### ISSUE THREAD

**Issue by reluuu** [yassouali/CCT#44]
Hi, thank you for your nice work!

I want to know how to save the image like (c),(d)
![image](https://user-images.githubusercontent.com/46579108/128638649-f142800d-c4f2-4cdf-b18a-8c6a1c06fabd.png)

Thanks!

**Comment by yassouali** [comment]
Hi @reluu

Unfortunately, I was not able to find the notebook that contains the computation, but it should be quite easy to replicate. For the features, at each spatial location, fetch the 8 neighboring features (so 3 x 3 window) and compute the averages differences. For the inputs, construct patches of size P x P at each pixel to simulate a given CNN receptive field, so each pixel will have a P² vector, then do the same computation.
