### ISSUE TITLE
How to obtain figure 2 (c) and (d)

### ISSUE THREAD

**Issue by tianyu0207** [yassouali/CCT#46]
Hi 

Congrats on the great work. 
Just wondering do you have the code to produce figure 2 (c) and (d) in your paper? We would like to generate similar figures for our project. 

Thanks

**Comment by yassouali** [comment]
Hi @tianyu0207 

Unfortunately, I was not able to find the notebook that contains the computation, but it should be quite easy to replicate. For the features, at each spatial location, fetch the 8 neighboring features (so 3 x 3 window) and compute the averages differences. For the inputs, construct patches of size P x P at each pixel to simulate a given CNN receptive field, so each pixel will have a P² vector, then do the same computation.
