### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorboard'

### ISSUE THREAD

**Issue by alqurri77** [yassouali/CCT#48]
Hi;

after running training command.. I got belw error: 

from torch.utils import tensorboard
  File "/.conda/envs/semiseg/lib/python3.6/site-packages/torch/utils/tensorboard/__init__.py", line 1, in <module>
    import tensorboard
ModuleNotFoundError: No module named 'tensorboard'

**Comment by yassouali** [comment]
Hi @alqurri77 

Maybe try updating the pytorch version you are using, this should be fixed with versions >= 1.2.0
