### ISSUE TITLE
Cityscapes/CamVid config file

### ISSUE THREAD

**Issue by ghost** [yassouali/CCT#49]
Hello, 

I'm interested in running additional experiments using CCT on Cityscapes and possibly CamVid. Could you please provide a config.json for this setting similar to what was provided for VOC?  

I expect to have to do some adjustments, but having the configuration you used would be much appreciated.

Thanks!

**Comment by yassouali** [comment]
Hi @blind-author

thank you for your intrest in our work

unfortunetely, i can't seem to find the version that was used for these experiments, however, to get the resutls, you simply need to adjust the dataloader of VOC for Cityscapes or CamVid and that it, from what i rember, the rest of the config are the same.

sorry for the delayed response

**Comment by alittledou** [comment]
> Hello,
> 
> I'm interested in running additional experiments using CCT on Cityscapes and possibly CamVid. Could you please provide a config.json for this setting similar to what was provided for VOC?
> 
> I expect to have to do some adjustments, but having the configuration you used would be much appreciated.
> 
> Thanks!

Hello,have you tried the best Settings
