### ISSUE TITLE
How to obtain figure 2(d)

### ISSUE THREAD

**Issue by reluuu** [yassouali/CCT#50]
Hi, thank you for your nice work!

I want to know how to produce figure2(d)? There are 2048 channels for hidden representation, how to visualize? Thanks for your help!

**Comment by yassouali** [comment]
Hi @reluuu 

Unfortunately, I was not able to find the notebook that contains the computation, but it should be quite easy to replicate. For the features, at each spatial location, fetch the 8 neighboring features (so 3 x 3 window) and compute the average of the L2 distances between the center the 8 neighboring features, so for each feature, you will get a scalar representing the distance between it and its neighboors; then normalize them and plot them. 

Hope this helps.

**Comment by reluuu** [comment]
Did you use dimension reduction like PCA to produce the figure?

**Comment by yassouali** [comment]
No we used the original features without any reduction, but using PCA might be a good idea

**Comment by reluuu** [comment]
But for the hidden representation, there are 2048 channels? How to visualize them in grayscale?

**Comment by yassouali** [comment]
at each spatial location, you compute the L2 distances between the feature i and its neighboors j, and use these distances, which are scalars, for ploting
