### ISSUE TITLE
Training model only on foreground labels

### ISSUE THREAD

**Issue by adagit12** [yassouali/CCT#55]
Hello Yassine,
I would like to ask you, what to change to train model only on foreground labels. My custom dataset consists of labels 0-4 with background (0 label).
Thank you for your help.

**Comment by yassouali** [comment]
Hi @adagit12 

In that case you can set ignore label index `ignore_index` to the background class, this will make the gradient of this class zero when the CE loss is computed [here](https://github.com/yassouali/CCT/blob/ef938b508ec339f40073cfc318f4224357cd10b7/utils/losses.py#L31)

**Comment by adagit12** [comment]
Thank you for your reply. Can I set this ignore_index from config file if I unterstood also ("ignore_index": 255), but instead 255 I set it to 0?

**Comment by yassouali** [comment]
yes that is correct
