### ISSUE TITLE
Adjust the number of decoders

### ISSUE THREAD

**Issue by 00000022234** [yassouali/CCT#58]
Hello! thank you for your great contribution to semi supervised semantic segmentation. How to adjust the parameters of the number of decoders in the code? And how to adjust the parameters of the number of noise? Thank you!

**Comment by yassouali** [comment]
hi @00000022234 

to adjust the parameters of the decoder, you'll need to change the config file in [configs](https://github.com/yassouali/CCT/tree/master/configs), for more details see the readme [here](https://github.com/yassouali/CCT#config-file-details-%EF%B8%8F)

**Comment by 00000022234** [comment]
@yassouali Thank you very much for your reply！ I ignored these important details .
