### ISSUE TITLE
custom dataset

### ISSUE THREAD

**Issue by rshivansh** [yassouali/CCT#6]
Hi @yassouali ,

- Thanks for the code. The paper is very clearly written. Thanks for the overall work.
- I was keen to try this on a custom data. Can you tell me what are the changes to be done for that?

Thanks

**Comment by yassouali** [comment]
Hi @rshivansh 

Thank you for your interest.

You'll need to create two dataloaders, one for your labeled examples and the other for the unlabeled examples. You can create them the same way you normally would. Then create then in `train.py` as `supervised_loader` and `unsupervised_loader`.

**Comment by rshivansh** [comment]
@yassouali thanks.
