### ISSUE TITLE
How can I train this model using my own dataset?

### ISSUE THREAD

**Issue by ChaikhiBelaid** [yassouali/CCT#60]
Hi, Thank you for this amzing work. I appreciate if you can explain how to train this model using my own dataset rather than voc data. Thank you in advance.

**Comment by yassouali** [comment]
Hi, thank you for your interest,
You can check the closed issues where you will find similar questions and their corresponding answers.

For example: check this [link](https://github.com/yassouali/CCT/issues?q=is%3Aissue+is%3Aclosed+custom).

Feel free to reopen the issue if you have more questions.
