### ISSUE TITLE
Errors while inferencing the trained model

### ISSUE THREAD

**Issue by tasveerahmad** [yassouali/CCT#66]
I run the code CCT and successfully trained the model. But when it comes to inferencing the Trained model, I am facing the error. The error report is attached herewith, 

**Loading pretrained model:models/backbones/pretrained/3x3resnet50-imagenet.pth
Some modules are missing: Error(s) in loading state_dict for DataParallel:**
	Unexpected key(s) in state_dict: "module.aux_decoders.0.upsample.0.weight", "module.aux_decoders.0.upsample.1.conv.weight", "module.aux_decoders.0.upsample.1.conv.bias", "module.aux_decoders.0.upsample.2.conv.weight", "module.aux_decoders.0.upsample.2.conv.bias", "module.aux_decoders.0.upsample.3.conv.weight", "module.aux_decoders.0.upsample.3.conv.bias", "module.aux_decoders.1.upsample.0.weight", "module.aux_decoders.1.upsample.1.conv.weight", "module.aux_decoders.1.upsample.1.conv.bias", "module.aux_decoders.1.upsample.2.conv.weight", "module.aux_decoders.1.upsample.2.conv.bias", "module.aux_decoders.1.upsample.3.conv.weight", "module.aux_decoders.1.upsample.3.conv.bias", "module.aux_decoders.2.upsample.0.weight", "module.aux_decoders.2.upsample.1.conv.weight", "module.aux_decoders.2.upsample.1.conv.bias", "module.aux_decoders.2.upsample.2.conv.weight", "module.aux_decoders.2.upsample.2.conv.bias", "module.aux_decoders.2.upsample.3.conv.weight", "module.aux_decoders.2.upsample.3.conv.bias", "module.aux_decoders.3.upsample.0.weight", "module.aux_decoders.3.upsample.1.conv.weight", "module.aux_decoders.3.upsample.1.conv.bias", "module.aux_decoders.3.upsample.2.conv.weight", "module.aux_decoders.3.upsample.2.conv.bias", "module.aux_decoders.3.upsample.3.conv.weight", "module.aux_decoders.3.upsample.3.conv.bias", "module.aux_decoders.4.upsample.0.weight", "module.aux_decoders.4.upsample.1.conv.weight", "module.aux_decoders.4.upsample.1.conv.bias", "module.aux_decoders.4.upsample.2.conv.weight", "module.aux_decoders.4.upsample.2.conv.bias", "module.aux_decoders.4.upsample.3.conv.weight", "module.aux_decoders.4.upsample.3.conv.bias", "module.aux_decoders.5.upsample.0.weight", "module.aux_decoders.5.upsample.1.conv.weight", "module.aux_decoders.5.upsample.1.conv.bias", "module.aux_decoders.5.upsample.2.conv.weight", "module.aux_decoders.5.upsample.2.conv.bias", "module.aux_decoders.5.upsample.3.conv.weight", "module.aux_decoders.5.upsample.3.conv.bias", "module.aux_decoders.6.upsample.0.weight", "module.aux_decoders.6.upsample.1.conv.weight", "module.aux_decoders.6.upsample.1.conv.bias", "module.aux_decoders.6.upsample.2.conv.weight", "module.aux_decoders.6.upsample.2.conv.bias", "module.aux_decoders.6.upsample.3.conv.weight", "module.aux_decoders.6.upsample.3.conv.bias", "module.aux_decoders.7.upsample.0.weight", "module.aux_decoders.7.upsample.1.conv.weight", "module.aux_decoders.7.upsample.1.conv.bias", "module.aux_decoders.7.upsample.2.conv.weight", "module.aux_decoders.7.upsample.2.conv.bias", "module.aux_decoders.7.upsample.3.conv.weight", "module.aux_decoders.7.upsample.3.conv.bias", "module.aux_decoders.8.upsample.0.weight", "module.aux_decoders.8.upsample.1.conv.weight", "module.aux_decoders.8.upsample.1.conv.bias", "module.aux_decoders.8.upsample.2.conv.weight", "module.aux_decoders.8.upsample.2.conv.bias", "module.aux_decoders.8.upsample.3.conv.weight", "module.aux_decoders.8.upsample.3.conv.bias", "module.aux_decoders.9.upsample.0.weight", "module.aux_decoders.9.upsample.1.conv.weight", "module.aux_decoders.9.upsample.1.conv.bias", "module.aux_decoders.9.upsample.2.conv.weight", "module.aux_decoders.9.upsample.2.conv.bias", "module.aux_decoders.9.upsample.3.conv.weight", "module.aux_decoders.9.upsample.3.conv.bias", "module.aux_decoders.10.upsample.0.weight", "module.aux_decoders.10.upsample.1.conv.weight", "module.aux_decoders.10.upsample.1.conv.bias", "module.aux_decoders.10.upsample.2.conv.weight", "module.aux_decoders.10.upsample.2.conv.bias", "module.aux_decoders.10.upsample.3.conv.weight", "module.aux_decoders.10.upsample.3.conv.bias", "module.aux_decoders.11.upsample.0.weight", "module.aux_decoders.11.upsample.1.conv.weight", "module.aux_decoders.11.upsample.1.conv.bias", "module.aux_decoders.11.upsample.2.conv.weight", "module.aux_decoders.11.upsample.2.conv.bias", "module.aux_decoders.11.upsample.3.conv.weight", "module.aux_decoders.11.upsample.3.conv.bias", "module.aux_decoders.12.upsample.0.weight", "module.aux_decoders.12.upsample.1.conv.weight", "module.aux_decoders.12.upsample.1.conv.bias", "module.aux_decoders.12.upsample.2.conv.weight", "module.aux_decoders.12.upsample.2.conv.bias", "module.aux_decoders.12.upsample.3.conv.weight", "module.aux_decoders.12.upsample.3.conv.bias", "module.aux_decoders.13.upsample.0.weight", "module.aux_decoders.13.upsample.1.conv.weight", "module.aux_decoders.13.upsample.1.conv.bias", "module.aux_decoders.13.upsample.2.conv.weight", "module.aux_decoders.13.upsample.2.conv.bias", "module.aux_decoders.13.upsample.3.conv.weight", "module.aux_decoders.13.upsample.3.conv.bias", "module.aux_decoders.14.upsample.0.weight", "module.aux_decoders.14.upsample.1.conv.weight", "module.aux_decoders.14.upsample.1.conv.bias", "module.aux_decoders.14.upsample.2.conv.weight", "module.aux_decoders.14.upsample.2.conv.bias", "module.aux_decoders.14.upsample.3.conv.weight", "module.aux_decoders.14.upsample.3.conv.bias", "module.aux_decoders.15.upsample.0.weight", "module.aux_decoders.15.upsample.1.conv.weight", "module.aux_decoders.15.upsample.1.conv.bias", "module.aux_decoders.15.upsample.2.conv.weight", "module.aux_decoders.15.upsample.2.conv.bias", "module.aux_decoders.15.upsample.3.conv.weight", "module.aux_decoders.15.upsample.3.conv.bias", "module.aux_decoders.16.upsample.0.weight", "module.aux_decoders.16.upsample.1.conv.weight", "module.aux_decoders.16.upsample.1.conv.bias", "module.aux_decoders.16.upsample.2.conv.weight", "module.aux_decoders.16.upsample.2.conv.bias", "module.aux_decoders.16.upsample.3.conv.weight", "module.aux_decoders.16.upsample.3.conv.bias", "module.aux_decoders.17.upsample.0.weight", "module.aux_decoders.17.upsample.1.conv.weight", "module.aux_decoders.17.upsample.1.conv.bias", "module.aux_decoders.17.upsample.2.conv.weight", "module.aux_decoders.17.upsample.2.conv.bias", "module.aux_decoders.17.upsample.3.conv.weight", "module.aux_decoders.17.upsample.3.conv.bias", "module.aux_decoders.18.upsample.0.weight", "module.aux_decoders.18.upsample.1.conv.weight", "module.aux_decoders.18.upsample.1.conv.bias", "module.aux_decoders.18.upsample.2.conv.weight", "module.aux_decoders.18.upsample.2.conv.bias", "module.aux_decoders.18.upsample.3.conv.weight", "module.aux_decoders.18.upsample.3.conv.bias", "module.aux_decoders.19.upsample.0.weight", "module.aux_decoders.19.upsample.1.conv.weight", "module.aux_decoders.19.upsample.1.conv.bias", "module.aux_decoders.19.upsample.2.conv.weight", "module.aux_decoders.19.upsample.2.conv.bias", "module.aux_decoders.19.upsample.3.conv.weight", "module.aux_decoders.19.upsample.3.conv.bias", "module.aux_decoders.20.upsample.0.weight", "module.aux_decoders.20.upsample.1.conv.weight", "module.aux_decoders.20.upsample.1.conv.bias", "module.aux_decoders.20.upsample.2.conv.weight", "module.aux_decoders.20.upsample.2.conv.bias", "module.aux_decoders.20.upsample.3.conv.weight", "module.aux_decoders.20.upsample.3.conv.bias", "module.aux_decoders.21.upsample.0.weight", "module.aux_decoders.21.upsample.1.conv.weight", "module.aux_decoders.21.upsample.1.conv.bias", "module.aux_decoders.21.upsample.2.conv.weight", "module.aux_decoders.21.upsample.2.conv.bias", "module.aux_decoders.21.upsample.3.conv.weight", "module.aux_decoders.21.upsample.3.conv.bias", "module.aux_decoders.22.upsample.0.weight", "module.aux_decoders.22.upsample.1.conv.weight", "module.aux_decoders.22.upsample.1.conv.bias", "module.aux_decoders.22.upsample.2.conv.weight", "module.aux_decoders.22.upsample.2.conv.bias", "module.aux_decoders.22.upsample.3.conv.weight", "module.aux_decoders.22.upsample.3.conv.bias", "module.aux_decoders.23.upsample.0.weight", "module.aux_decoders.23.upsample.1.conv.weight", "module.aux_decoders.23.upsample.1.conv.bias", "module.aux_decoders.23.upsample.2.conv.weight", "module.aux_decoders.23.upsample.2.conv.bias", "module.aux_decoders.23.upsample.3.conv.weight", "module.aux_decoders.23.upsample.3.conv.bias", "module.aux_decoders.24.upsample.0.weight", "module.aux_decoders.24.upsample.1.conv.weight", "module.aux_decoders.24.upsample.1.conv.bias", "module.aux_decoders.24.upsample.2.conv.weight", "module.aux_decoders.24.upsample.2.conv.bias", "module.aux_decoders.24.upsample.3.conv.weight", "module.aux_decoders.24.upsample.3.conv.bias", "module.aux_decoders.25.upsample.0.weight", "module.aux_decoders.25.upsample.1.conv.weight", "module.aux_decoders.25.upsample.1.conv.bias", "module.aux_decoders.25.upsample.2.conv.weight", "module.aux_decoders.25.upsample.2.conv.bias", "module.aux_decoders.25.upsample.3.conv.weight", "module.aux_decoders.25.upsample.3.conv.bias", "module.aux_decoders.26.upsample.0.weight", "module.aux_decoders.26.upsample.1.conv.weight", "module.aux_decoders.26.upsample.1.conv.bias", "module.aux_decoders.26.upsample.2.conv.weight", "module.aux_decoders.26.upsample.2.conv.bias", "module.aux_decoders.26.upsample.3.conv.weight", "module.aux_decoders.26.upsample.3.conv.bias", "module.aux_decoders.27.upsample.0.weight", "module.aux_decoders.27.upsample.1.conv.weight", "module.aux_decoders.27.upsample.1.conv.bias", "module.aux_decoders.27.upsample.2.conv.weight", "module.aux_decoders.27.upsample.2.conv.bias", "module.aux_decoders.27.upsample.3.conv.weight", "module.aux_decoders.27.upsample.3.conv.bias", "module.aux_decoders.28.upsample.0.weight", "module.aux_decoders.28.upsample.1.conv.weight", "module.aux_decoders.28.upsample.1.conv.bias", "module.aux_decoders.28.upsample.2.conv.weight", "module.aux_decoders.28.upsample.2.conv.bias", "module.aux_decoders.28.upsample.3.conv.weight", "module.aux_decoders.28.upsample.3.conv.bias", "module.aux_decoders.29.upsample.0.weight", "module.aux_decoders.29.upsample.1.conv.weight", "module.aux_decoders.29.upsample.1.conv.bias", "module.aux_decoders.29.upsample.2.conv.weight", "module.aux_decoders.29.upsample.2.conv.bias", "module.aux_decoders.29.upsample.3.conv.weight", "module.aux_decoders.29.upsample.3.conv.bias". 
0it [00:00, ?it/s]

I searched this error on internet and tried to fix it by changing the argument of model.load_state_dict(checkpoint['state_dict'], strict=False/True ), but either way it didn't work out. Please help if I could fix this issue.

**Comment by yassouali** [comment]
Hi @tasveerahmad 
Can you please double check the config fine is the same, here it seems all aux decoder are not laoder, maybe in the config you are in supervised mode.
Hope this helps.
