### ISSUE TITLE
Question about the paper "Semi-Supervised Semantic Segmentation with Cross-Consistency Training"

### ISSUE THREAD

**Issue by Hugo-cell111** [yassouali/CCT#68]
Hi! Could I ask how the images in row(d) from Figure 2 are drawn? The resolution of the intermediate representations seems not the same as the resolution of input images. In other word, how can I expand the resolution of the hidden representations to the same shape as the input images? Thanks!

**Comment by yassouali** [comment]
Hi @Hugo-cell111 

You can either upsample the features then compute the distances or compute the distances then upsample them, the upsampling is only done for better visualization, you can even just apply TSNE / PCA over the features to see the clustering of the features

Hope this helps
