### ISSUE TITLE
Training on custom datasets in CCT.

### ISSUE THREAD

**Issue by TinaWut** [yassouali/CCT#70]
First of all, thank you very much for sharing your paper and code. I have also read the previous answers regarding issues with training on custom datasets, but I still haven't resolved the problems I encountered during my own dataset training.

My dataset has two classes (0 for background, 1 for another category). I modified num_classes = 2 in voc.py and also adjusted the color mapping in palette.py with def get_voc_palette(num_classes) to represent two classes (black and white). I am training using a supervised approach, but I am encountering a situation where the intersection over union (IoU) for one of the classes is 0. Additionally, when loading the same model weights in inference.py, the output results vary with each run. I have no idea how to resolve these issues. Any guidance would be greatly appreciated
![微信图片_20240104212524](https://github.com/yassouali/CCT/assets/100891902/2474a50d-e904-404d-b6f3-c4a587c9dac9)
![Uploading 微信截图_20240104212624.png…]()

**Comment by TinaWut** [comment]
![Uploading 微信截图_20240104212624.png…]()

**Comment by TinaWut** [comment]
![微信截图_20240104212624](https://github.com/yassouali/CCT/assets/100891902/42ebd436-c19d-4d1b-9bdf-1a97c3def50b)

**Comment by TinaWut** [comment]
The code issue has been resolved

**Comment by yassouali** [comment]
Hi @TinaWut, happy to hear that the problem was resolved, I'll close the issue for now

**Comment by 79zzz** [comment]
您好，请问你是如何自定义数据集的
